summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-android-34-aarch64/releases/download/2025.01.24/pkg-config-0.29.2-android-34-arm64-v8a.release.tar.xz
bin-sha: 3156301a3a8f8ad263014fdacb4544bb7f2bb76fb49b2101cf76c04841b33b3e
